/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.Flora.kotlin.cp1

import java.io.File

data class Answer(val problemNumber: Int, val answer: Char)

fun main() {
    val inputFile = File("testdata.in")
    val lines = inputFile.readLines()
    var index = 0
    val t = lines[index++].toInt()
    var case = 1
    repeat(t) {
        val n = lines[index++].toInt()
        val answers = mutableListOf<Answer>()
        repeat(n) {
            val (problemNumber, answer) = lines[index++].split(". ")
            answers.add(Answer(problemNumber.toInt(), answer[0]))
        }
        val sortedAnswers = answers.sortedBy { it.problemNumber }
        println("Case #$case:")
        sortedAnswers.forEach { println("${it.problemNumber}. ${it.answer}") }
        case++
    }
}

